// Dependencies
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.css";

// UI Components
import { Navbar } from "@/components/common/Navbar";

// Constants
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

config.autoAddCss = false

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
